name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13.3
  - pandas=2.2.3
  - pytest=8.3.5
  - scipy=1.15.2
  - pip=25.1.1
  - pip:
      - mlflow==2.22.0
      - wandb==0.19.10