name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - hydra-core=1.3.2
  - matplotlib=3.10.3
  - pandas=2.2.3
  - scikit-learn=1.6.1
  - pip=25.1.1
  - pip:
      - mlflow==2.22.0
      - wandb==0.19.11
